json.id track.id
json.released_at track.created_at
json.title track.title
json.provider track.social_link.provider
json.provider_url track.provider_url
json.stream_url track.stream_url
json.download_url track.download_url
json.artwork_url artwork_track_url(track)
json.waveform_url waveform_track_url(track)